CREATE TABLE USER_GROUP (
  USER_GROUP_ID BIGINT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(64) NOT NULL
  , PERMISSION TEXT
  , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_BY BIGINT NOT NULL DEFAULT 1,
  
  PRIMARY KEY (USER_GROUP_ID)
);

--
-- Table structure for table `USERS`
--

CREATE TABLE USERS (
       USER_ID BIGINT NOT NULL AUTO_INCREMENT 
     , USER_GROUP_ID BIGINT NOT NULL 
     , USER_NAME VARCHAR(100)
     , PASSWORD VARCHAR(50) NOT NULL DEFAULT '1234'
     , FIRST_NAME VARCHAR(50) NOT NULL
     , LAST_NAME VARCHAR(50) NOT NULL
     , MIDDLE_NAME VARCHAR(50) 
     , PICTURE VARCHAR(150) DEFAULT 'user.jpg'  
     , EMAIL VARCHAR(100)
     , CURRENT_LOCALE VARCHAR(10)
     , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
     , MOD_DATE TIMESTAMP NOT NULL  
     , BIRTH_DATE DATE NOT NULL
     , SEX CHAR(1) NOT NULL   
     , MOD_BY BIGINT NOT NULL DEFAULT 1
     , HOME_PHONE VARCHAR(20)
     , MOBILE_PHONE VARCHAR(20)
     , ADDRESS TEXT
     , CITY VARCHAR(150) 
     , COUNTRY_ID BIGINT DEFAULT 215
     , ZIP_CODE  VARCHAR(10) 
     , STATUS SMALLINT DEFAULT 0
     , PRIMARY KEY (USER_ID) 
     , CONSTRAINT FK_USER_1 FOREIGN KEY (USER_GROUP_ID)
                  REFERENCES USER_GROUP (USER_GROUP_ID)
); 
ALTER TABLE USERS MODIFY COLUMN STATUS SMALLINT DEFAULT 1
      COMMENT '0-Pending Approval, 1- Approved/Active, 2- Rejected, 3- Inactive/Deactivated';
CREATE UNIQUE INDEX UNIQUE_USER ON USERS (EMAIL ASC);
CREATE UNIQUE INDEX UNIQUE_USER_NAME ON USERS (USER_NAME ASC);