DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_GROUP;
DROP TABLE IF EXISTS USER_GROUP;
DROP TABLE IF EXISTS USER_GROUP;
DROP TABLE IF EXISTS USER_GROUP;
DROP TABLE IF EXISTS USER_GROUP;
DROP TABLE IF EXISTS USER_GROUP;
DROP TABLE IF EXISTS USER_GROUP;
DROP TABLE IF EXISTS USER_GROUP;

CREATE TABLE WEEK_DAY (
  WEEK_DAY_ID TINYINT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(64) NOT NULL
  , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_BY BIGINT NOT NULL DEFAULT 1,
  
  PRIMARY KEY (WEEK_DAY_ID)
);


CREATE TABLE COUNTRY (
       COUNTRY_ID BIGINT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(100) NOT NULL
     , DOMAIN CHAR(2)
     , CREATE_DATE TIMESTAMP NOT NULL
     , MOD_DATE TIMESTAMP NOT NULL
     , MOD_BY BIGINT NOT NULL
     , PRIMARY KEY (COUNTRY_ID)
); 


CREATE TABLE DEPARTMENT (
  DEPARTMENT_ID BIGINT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(64) NOT NULL
  , DESCRIPTION TEXT
  , STATUS SMALLINT DEFAULT 0
  , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_BY BIGINT NOT NULL DEFAULT 1,
  
  PRIMARY KEY (DEPARTMENT_ID)
);


CREATE TABLE USER_GROUP (
  USER_GROUP_ID BIGINT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(64) NOT NULL
  , PERMISSION TEXT
  , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_BY BIGINT NOT NULL DEFAULT 1,
  
  PRIMARY KEY (USER_GROUP_ID)
);

--
-- Table structure for table `USERS`
--

CREATE TABLE USERS (
       USER_ID BIGINT NOT NULL AUTO_INCREMENT 
     , USER_GROUP_ID BIGINT NOT NULL 
     , USER_NAME VARCHAR(100)
     , PASSWORD VARCHAR(50) NOT NULL
     , FIRST_NAME VARCHAR(50) NOT NULL
     , LAST_NAME VARCHAR(50) NOT NULL
     , MIDDLE_NAME VARCHAR(50) 
     , PICTURE VARCHAR(50) DEFAULT 'user.jpg'  
     , EMAIL VARCHAR(100)
     , CURRENT_LOCALE VARCHAR(10)
     , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
     , MOD_DATE TIMESTAMP NOT NULL  
     , BIRTH_DATE TIMESTAMP
     , SEX CHAR(1) NOT NULL   
     , MOD_BY BIGINT NOT NULL DEFAULT 1
     , HOME_PHONE VARCHAR(20)
     , MOBILE_PHONE VARCHAR(20)
     , ADDRESS TEXT
     , CITY VARCHAR(150) 
     , COUNTRY_ID BIGINT DEFAULT 215
     , ZIP_CODE  VARCHAR(10) 
     , STATUS SMALLINT DEFAULT 0
     , PRIMARY KEY (USER_ID) 
     , CONSTRAINT FK_USER_1 FOREIGN KEY (USER_GROUP_ID)
                  REFERENCES USER_GROUP (USER_GROUP_ID)
); 
ALTER TABLE USERS MODIFY COLUMN STATUS SMALLINT DEFAULT 1
      COMMENT '0-Pending Approval, 1- Approved/Active, 2- Rejected, 3- Inactive/Deactivated';
CREATE UNIQUE INDEX UNIQUE_USER ON USERS (EMAIL ASC);
CREATE UNIQUE INDEX UNIQUE_USER_NAME ON USERS (USER_NAME ASC);
-----------------------------------------------------------


--
-- Table structure for table `USERS`
--

CREATE TABLE EMPLOYEE (
       EMPLOYEE_ID BIGINT NOT NULL AUTO_INCREMENT 
     , USER_ID BIGINT NOT NULL 
     , DESIGNATION VARCHAR(100)
     , DEPARTMENT_ID BIGINT NOT NULL
     , SHORT_BIOGRAPHIE TEXT
     , SPECIALIST VARCHAR(100)
     , BLOOD_GROUP VARCHAR(2)
     , RESUME TEXT
     , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
	 , STATUS SMALLINT DEFAULT 0
     , PRIMARY KEY (EMPLOYEE_ID)
     , CONSTRAINT FK_EMPLOYEE_1 FOREIGN KEY (USER_ID)
                  REFERENCES USERS (USER_ID)
     , CONSTRAINT FK_EMPLOYEE_2 FOREIGN KEY (DEPARTMENT_ID)
                  REFERENCES DEPARTMENT (DEPARTMENT_ID)
);

CREATE TABLE PATIENT (
       PATIENT_ID BIGINT NOT NULL AUTO_INCREMENT 
     , MATRICULE VARCHAR(20) NOT NULL
     , USER_ID BIGINT NOT NULL 
     , CONTACT VARCHAR(100)
     , CONTACT_PHONE VARCHAR(20)
     , MEDICAL_HISTORY TEXT
     , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
	 , STATUS SMALLINT DEFAULT 0
     , PRIMARY KEY (PATIENT_ID)
     , CONSTRAINT FK_PATIENT_1 FOREIGN KEY (USER_ID)
                  REFERENCES USERS (USER_ID)
);

CREATE TABLE DOCUMENT (
	   DOCUMENT_ID BIGINT NOT NULL AUTO_INCREMENT 
     , PATIENT_ID BIGINT NOT NULL 
     , DOCTOR_ID BIGINT 
     , FILE_LOCATION VARCHAR(250)
     , DESCRIPTION TEXT
     , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
	 , STATUS SMALLINT DEFAULT 0
     , PRIMARY KEY (DOCUMENT_ID)
     , CONSTRAINT FK_DOCUMENT_1 FOREIGN KEY (PATIENT_ID)
                  REFERENCES PATIENT (PATIENT_ID)
     , CONSTRAINT FK_DOCUMENT_2 FOREIGN KEY (DOCTOR_ID)
                  REFERENCES EMPLOYEE (EMPLOYEE_ID)
);

CREATE TABLE SCHEDULE (
	   SCHEDULE_ID BIGINT NOT NULL AUTO_INCREMENT 
     , DOCTOR_ID BIGINT NOT NULL
     , WEEK_DAY_ID TINYINT NOT NULL
     , BEGIN_TIME VARCHAR(5) NOT NULL
     , END_TIME VARCHAR(5) NOT NULL
     , PER_PATIENT_TIME VARCHAR(5) NOT NULL
     , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
	 , STATUS SMALLINT DEFAULT 0
     , PRIMARY KEY (SCHEDULE_ID)
     , CONSTRAINT FK_SCHEDULE_1 FOREIGN KEY (DOCTOR_ID)
                  REFERENCES EMPLOYEE (EMPLOYEE_ID)
     , CONSTRAINT FK_SCHEDULE_2 FOREIGN KEY (WEEK_DAY_ID)
                  REFERENCES WEEK_DAY (WEEK_DAY_ID)
);

CREATE TABLE APPOINTMENT (
	   APPOINTMENT_ID BIGINT NOT NULL AUTO_INCREMENT 
     , PATIENT_ID BIGINT NOT NULL 
     , DOCTOR_ID BIGINT NOT NULL
     , DEPARTMENT_ID BIGINT NOT NULL
     , APOINTMENT_DATE VARCHAR(250) NOT NULL
     , BEGIN_TIME VARCHAR(5) NOT NULL
     , END_TIME VARCHAR(5) NOT NULL
     , PROBLEM TEXT
     , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
	 , STATUS SMALLINT DEFAULT 0
     , PRIMARY KEY (APPOINTMENT_ID)
     , CONSTRAINT FK_APPOINTMENT_1 FOREIGN KEY (PATIENT_ID)
                  REFERENCES PATIENT (PATIENT_ID)
     , CONSTRAINT FK_APPOINTMENT_2 FOREIGN KEY (DOCTOR_ID)
                  REFERENCES EMPLOYEE (EMPLOYEE_ID)
     , CONSTRAINT FK_APPOINTMENT_3 FOREIGN KEY (DEPARTMENT_ID)
                  REFERENCES DEPARTMENT (DEPARTMENT_ID)
);

CREATE TABLE CASE_STUDY (
	   CASE_STUDY_ID BIGINT NOT NULL AUTO_INCREMENT 
     , PATIENT_ID BIGINT NOT NULL 
     , FOOD_ALLERGIES VARCHAR(250) 
     , TENDENCY_BLEED VARCHAR(250) 
     , HEART_DISEASES VARCHAR(250) 
     , HIGH_BLOOD_PRESSURE VARCHAR(250) 
     , DIABETIC VARCHAR(250) 
     , SURGERY VARCHAR(250) 
     , ACCIDENT VARCHAR(250) 
     , OTHERS VARCHAR(250) 
     , FAMILY_MEDICAL_HISTORY VARCHAR(250) 
     , CURRENT_MEDICATION VARCHAR(250) 
     , FEMALE_PREGNANCY VARCHAR(250) 
     , BREAST_FEEDING VARCHAR(250) 
     , HEALTH_INSURANCE VARCHAR(250) 
     , LOW_INCOME VARCHAR(250) 
     , REFERENCE VARCHAR(250) 
     , STATUS SMALLINT DEFAULT 0
     , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
     , PRIMARY KEY (CASE_STUDY_ID)
     , CONSTRAINT FK_CASE_STUDY_1 FOREIGN KEY (PATIENT_ID)
                  REFERENCES PATIENT (PATIENT_ID)
);


CREATE TABLE CATEGORY (
  CATEGORY_ID BIGINT NOT NULL AUTO_INCREMENT
  , PARENT_CATEGORY_ID BIGINT
  , NAME VARCHAR(64) NOT NULL
  , DESCRIPTION TEXT
  , STATUS SMALLINT DEFAULT 0
  , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_BY BIGINT NOT NULL DEFAULT 1
  , PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE MANUFACTURER (
  MANUFACTURER_ID BIGINT NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(64) NOT NULL
  , DESCRIPTION TEXT
  , STATUS SMALLINT DEFAULT 0
  , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_BY BIGINT NOT NULL DEFAULT 1
  , PRIMARY KEY (MANUFACTURER_ID)
);

CREATE TABLE MEDICINE (
  MEDICINE_ID BIGINT NOT NULL AUTO_INCREMENT
  , CATEGORY_ID BIGINT NOT NULL
  , MANUFACTURER_ID BIGINT NOT NULL
  , NAME VARCHAR(64) NOT NULL
  , DESCRIPTION TEXT
  , PRICE DOUBLE
  , STATUS SMALLINT DEFAULT 0
  , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
  , MOD_BY BIGINT NOT NULL DEFAULT 1
  , PRIMARY KEY (MEDICINE_ID)
  , CONSTRAINT FK_MEDICINE_1 FOREIGN KEY (CATEGORY_ID)
                  REFERENCES CATEGORY (CATEGORY_ID)
  , CONSTRAINT FK_MEDICINE_2 FOREIGN KEY (MANUFACTURER_ID)
                  REFERENCES MANUFACTURER (MANUFACTURER_ID)
);

CREATE TABLE PRESCRIPTION (
	   PRESCRIPTION_ID BIGINT NOT NULL AUTO_INCREMENT 
     , APPOINTMENT_ID BIGINT NOT NULL 
     , PATIENT_ID BIGINT NOT NULL 
     , WEIGHT TINYINT
     , BLOOD_PRESSURE VARCHAR(20)
     , REFERENCE VARCHAR(120)
     , NUMBER_OF_TIME TINYINT NOT NULL DEFAULT 1
	 , PRESCRIPTION_TYPE SMALLINT DEFAULT 0
	 , CHIEF_COMPLAIN VARCHAR(250)
	 , VISITING_FEES DOUBLE
	 , PATIENT_NOTES VARCHAR(500)
	 , STATUS SMALLINT DEFAULT 0
	 , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
     , PRIMARY KEY (PRESCRIPTION_ID)
     , CONSTRAINT FK_PRESCRIPTION_1 FOREIGN KEY (APPOINTMENT_ID)
                  REFERENCES APPOINTMENT (APPOINTMENT_ID)
     , CONSTRAINT FK_PRESCRIPTION_2 FOREIGN KEY (PATIENT_ID)
                  REFERENCES PATIENT (PATIENT_ID)
);

CREATE TABLE PRESCRIPTION_MEDICINE (
	   PRESCRIPTION_MEDICINE_ID BIGINT NOT NULL AUTO_INCREMENT 
	 , PRESCRIPTION_ID BIGINT NOT NULL 
	 , MEDICINE_ID BIGINT NOT NULL 
	 , INSTRUCTIONS VARCHAR(250) NOT NULL
	 , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
   , PRIMARY KEY (PRESCRIPTION_MEDICINE_ID)
   , CONSTRAINT FK_PRESCRIPTION_MEDICINE_1 FOREIGN KEY (PRESCRIPTION_ID)
                  REFERENCES PRESCRIPTION (PRESCRIPTION_ID)
   , CONSTRAINT FK_PRESCRIPTION_MEDICINE_2 FOREIGN KEY (MEDICINE_ID)
                  REFERENCES MEDICINE (MEDICINE_ID)
);

CREATE TABLE PRESCRIPTION_DIAGNOSIS (
	   PRESCRIPTION_DIAGNOSIS_ID BIGINT NOT NULL AUTO_INCREMENT 
	 , PRESCRIPTION_ID BIGINT NOT NULL 
	 , DIAGNOSIS VARCHAR(100) NOT NULL
	 , INSTRUCTIONS VARCHAR(250) NOT NULL
	 , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
   , PRIMARY KEY (PRESCRIPTION_DIAGNOSIS_ID)
   , CONSTRAINT FK_PRESCRIPTION_DIAGNOSIS_1 FOREIGN KEY (PRESCRIPTION_ID)
                  REFERENCES PRESCRIPTION (PRESCRIPTION_ID)
);

CREATE TABLE APPOINTMENT_DIAGNOSIS (
	   APPOINTMENT_DIAGNOSIS_ID BIGINT NOT NULL AUTO_INCREMENT 
	 , APPOINTMENT_ID BIGINT NOT NULL 
	 , DIAGNOSIS VARCHAR(100) NOT NULL 
	 , INTRUCTIONS VARCHAR(250) NOT NULL
	 , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW()
	 , MOD_BY BIGINT NOT NULL DEFAULT 1	
   , PRIMARY KEY (APPOINTMENT_DIAGNOSIS_ID)
   , CONSTRAINT FK_APPOINTMENT_DIAGNOSIS_1 FOREIGN KEY (APPOINTMENT_ID)
               REFERENCES APPOINTMENT (APPOINTMENT_ID)
);

commit;